import { View, Text, FlatList, TouchableOpacity, Image, StyleSheet } from "react-native";
import { useEffect, useState } from "react";

export default function HomeScreen() {
  const [listings, setListings] = useState<any[]>([]);

    useEffect(() => {
        fetchListings();
          }, []);

            const fetchListings = async () => {
                try {
                      const res = await fetch(
                              "https://api.realtyapi.io/v1/properties?city=Mandeville&state=LA&limit=20",
                                      {
                                                headers: {
                                                            "x-api-key": "rt_4qSHaG4OQ4zPDWXKJ9PKEgVE",
                                                                      },
                                                                              }
                                                                                    );

                                                                                          const data = await res.json();

                                                                                                const formatted =
                                                                                                        data?.results?.map((item: any, i: number) => ({
                                                                                                                  id: i.toString(),
                                                                                                                            price: item?.list_price || 300000,
                                                                                                                                      beds: item?.beds || 3,
                                                                                                                                                baths: item?.baths || 2,
                                                                                                                                                          address: item?.location?.city || "Mandeville, LA",
                                                                                                                                                                    image: `https://source.unsplash.com/400x250/?house,${i}`,
                                                                                                                                                                            })) || [];

                                                                                                                                                                                  // ✅ Fallback if API empty
                                                                                                                                                                                        if (formatted.length === 0) {
                                                                                                                                                                                                const fakeList = Array.from({ length: 6 }).map((_, i) => ({
                                                                                                                                                                                                          id: i.toString(),
                                                                                                                                                                                                                    price: 250000 + i * 15000,
                                                                                                                                                                                                                              beds: 3,
                                                                                                                                                                                                                                        baths: 2,
                                                                                                                                                                                                                                                  address: "Mandeville, LA",
                                                                                                                                                                                                                                                            image: `https://source.unsplash.com/400x250/?house,${i}`,
                                                                                                                                                                                                                                                                    }));

                                                                                                                                                                                                                                                                            setListings(fakeList);
                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                          setListings(formatted);
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                          console.log("Error fetching listings:", error);

                                                                                                                                                                                                                                                                                                                // fallback on error too
                                                                                                                                                                                                                                                                                                                      const fakeList = Array.from({ length: 6 }).map((_, i) => ({
                                                                                                                                                                                                                                                                                                                              id: i.toString(),
                                                                                                                                                                                                                                                                                                                                      price: 250000 + i * 15000,
                                                                                                                                                                                                                                                                                                                                              beds: 3,
                                                                                                                                                                                                                                                                                                                                                      baths: 2,
                                                                                                                                                                                                                                                                                                                                                              address: "Mandeville, LA",
                                                                                                                                                                                                                                                                                                                                                                      image: `https://source.unsplash.com/400x250/?house,${i}`,
                                                                                                                                                                                                                                                                                                                                                                            }));

                                                                                                                                                                                                                                                                                                                                                                                  setListings(fakeList);
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                          const renderItem = ({ item }: any) => (
                                                                                                                                                                                                                                                                                                                                                                                              <TouchableOpacity style={styles.card}>
                                                                                                                                                                                                                                                                                                                                                                                                    <Image source={{ uri: item.image }} style={styles.image} />
                                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.info}>
                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.price}>${item.price.toLocaleString()}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.address}>{item.address}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.details}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {item.beds} beds • {item.baths} baths
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View style={styles.container}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.title}>Discover Homes</Text>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          data={listings}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keyExtractor={(item) => item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderItem={renderItem}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#0f172a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            card: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#1e293b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            overflow: "hidden",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 150,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            info: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    address: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#94a3b8",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            details: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "#cbd5f5",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });